"""feed_source_rows + feed_source_sync_runs — 외부 사료 관측의 불변 revision 저장 + 동기화 원장 (P-1 topology C)

docs/feed/FEED_PERSISTENCE_ARCHITECTURE.md (2026-09-22). 쓰기 규칙: INSERT 만(정정 = 새 revision, 삭제 = RETRACTED tombstone).
quantity_basis 는 행의 속성(AS_RECORDED|DELIVERED|CONSUMED) · currency NOT NULL(소스 계약) · feed_records 무변경.
★ 프로덕션 적용은 별도 결재. 이 파일은 로컬 upgrade/downgrade 검증만 됐다.

Revision ID: a7c9e1f3b5d7
Revises: f3c6a8d0b2e4
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7c9e1f3b5d7'
down_revision: str | None = 'f3c6a8d0b2e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_source_sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=20), nullable=False),
    sa.Column('source_dataset', sa.String(length=40), nullable=False),
    sa.Column('source_contract_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('watermark_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watermark_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('farms', sa.Integer(), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_unchanged', sa.Integer(), nullable=False),
    sa.Column('rows_superseded', sa.Integer(), nullable=False),
    sa.Column('rows_retracted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCEEDED', 'SOURCE_UNAVAILABLE', 'SYNC_FAILED')", name='ck_fssr_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fssr_source_started', 'feed_source_sync_runs', ['source_system', 'source_dataset', 'started_at'], unique=False)
    op.create_table('feed_source_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=20), nullable=False),
    sa.Column('source_dataset', sa.String(length=40), nullable=False),
    sa.Column('source_row_key', sa.String(length=64), nullable=False),
    sa.Column('source_contract_version', sa.String(length=40), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_run_id', sa.UUID(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_raw', sa.String(length=32), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_unit', sa.String(length=8), nullable=False),
    sa.Column('quantity_basis', sa.String(length=12), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('feed_stage_raw', sa.String(length=50), nullable=True),
    sa.Column('feed_product_raw', sa.String(length=200), nullable=True),
    sa.Column('source_status', sa.String(length=10), nullable=False),
    sa.Column('quantity_status', sa.String(length=12), nullable=False),
    sa.Column('cost_status', sa.String(length=12), nullable=False),
    sa.Column('quality_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_inserted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cost_status IN ('ACCEPTED', 'INSUFFICIENT', 'EXCLUDED')", name='ck_fsr_cost_status'),
    sa.CheckConstraint("quantity_basis IN ('AS_RECORDED', 'DELIVERED', 'CONSUMED')", name='ck_fsr_basis'),
    sa.CheckConstraint("quantity_status IN ('ACCEPTED', 'EXCLUDED')", name='ck_fsr_quantity_status'),
    sa.CheckConstraint("source_status IN ('ACTIVE', 'INACTIVE', 'RETRACTED')", name='ck_fsr_source_status'),
    sa.CheckConstraint('revision >= 1', name='ck_fsr_revision'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['feed_source_sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_dataset', 'source_row_key', 'payload_hash', name='uq_fsr_identity_payload'),
    sa.UniqueConstraint('source_system', 'source_dataset', 'source_row_key', 'revision', name='uq_fsr_identity_revision')
    )
    op.create_index('idx_fsr_farm_basis_date', 'feed_source_rows', ['farm_id', 'quantity_basis', 'event_date'], unique=False, postgresql_where="is_current AND source_status = 'ACTIVE'")
    op.create_index('uq_fsr_identity_current', 'feed_source_rows', ['source_system', 'source_dataset', 'source_row_key'], unique=True, postgresql_where='is_current')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_fsr_identity_current', table_name='feed_source_rows', postgresql_where='is_current')
    op.drop_index('idx_fsr_farm_basis_date', table_name='feed_source_rows', postgresql_where="is_current AND source_status = 'ACTIVE'")
    op.drop_table('feed_source_rows')
    op.drop_index('idx_fssr_source_started', table_name='feed_source_sync_runs')
    op.drop_table('feed_source_sync_runs')
    # ### end Alembic commands ###
